### ISSUE TITLE
1/40th config with existing yr156 ACCESS-OM2-01 forcing?

### ISSUE THREAD

**Issue by adele157** [COSIMA/mom6-panan#29] opened 2023-03-14 01:03 UTC
The Sapphire Rapid nodes are now online, so there is a bit of time pressure to get things going. (Though I have yet to hear from Ben or Al that they're ready for us.)

We had hoped to use year 2 boundary forcing (either OM4 or ACCESS-OM2-01), so that we have a boundary condition closer to obs with less bias. However we're struggling to get that working.

Should we consider an alternative option using the existing yr 156 forcing on the 1/40th config, so at least we can run something? I can no longer find the raw ACCESS-OM2-01 yr 156 data, which I think may have been deleted. However we could interpolate the existing 1/20th forcing (/g/data/x77/ahg157/inputs/mom6/panan/forcing_obc_shifted.nc) onto the 1/40th grid.

We know that the run with the yr 156 forcing data has a large drift at the northern boundary, but if our focus is on the Antarctic shelf and slope processes in the upper ocean, perhaps that doesn't matter so much. It would be useful to plot some trend plots of circulation and T/S near the Antarctic slope at a few different depths (perhaps 500m, 1000m, 2000m) for the first 10-20 years of the panant-01-zstar-v13 simulation to see if drift is an issue there.

**Comment by PaulSpence** [comment] 2023-03-14 03:32
I think running something is better than nothing. There are no guarantees that the 2 year boundary forcing won't drift even if they worked. Also, we will learn something regardless of the drift by running the simulation (we will probably mess something else up in the simulation anyway). I will aim to check the drift near the slope in the first 10-20 years of the panant-01-zstar-v13 simulation.

**Comment by adele157** [comment] 2023-03-14 03:43
Awesome thanks Paul! I have also just started a 1/20th case with the new
topography and old yr 156 ACCESS-OM2-01 initial conditions and boundary
forcing. Once that runs out a way we can also check the drift in that near
the slope.

**Comment by adele157** [comment] 2023-03-15 00:31
@willaguiar has most of the 1/40th files ready to go (bathymetry, masks, runoff) and will work on interpolating the boundary forcing (`/g/data/x77/ahg157/inputs/mom6/panan/forcing_obc_shifted.nc`) and initial conditions (`/g/data/x77/ahg157/inputs/mom6/panan/temp_salt_init_z_0025_filled_NaNs.nc`) from the [1/20th config](https://github.com/COSIMA/mom6-panan/tree/test-1/20deg).

The one thing we're not sure about is how we decide on the tile layout and generate the mask_table file for the 1/40th. @micaeljtoliveira @angus-g any chance that one of you could jump onto this for us?

**Comment by micaeljtoliveira** [comment] 2023-03-15 02:23
> The one thing we're not sure about is how we decide on the tile layout and generate the mask_table file for the 1/40th. 

Would this be the processor layout and mask?

**Comment by adele157** [comment] 2023-03-15 02:36
> Would this be the processor layout and mask?

Yes, that's it @micaeljtoliveira.

**Comment by micaeljtoliveira** [comment] 2023-03-15 05:05
I can have a go at it. Can you just point out where I can find the grid and topography files?

**Comment by adele157** [comment] 2023-03-15 05:20
Thanks @micaeljtoliveira! It's [this config](https://github.com/COSIMA/mom6-panan/blob/test-1/20deg/). Currently it's very messy pointing to multiple directories with identically named (but different data) files! :grimacing:

From what I can tell it is using `/g/data/e14/cs6673/panan-005/domain-tools/new_topog/ topog.nc` and `/g/data/e14/cs6673/panan-005/domain-tools/new_topog/ ocean_hgrid_0025.nc`.

**Comment by micaeljtoliveira** [comment] 2023-03-16 00:41
@adele157 Sorry,  I'm a bit confused here. The files `/g/data/e14/cs6673/panan-005/domain-tools/new_topog/topog.nc` and `/g/data/e14/cs6673/panan-005/domain-tools/new_topog/ocean_hgrid_0025.nc` are for a 1/20deg resolution, but I would need the 1/40deg files. Maybe @willaguiar could point me in the right direction?

**Comment by adele157** [comment] 2023-03-16 00:44
Ooops, sorry, brain was clearly not working!

I think they are these ones (@willaguiar can confirm these are the latest versions):
`/scratch/g40/wf4500/mom6_topo/shared/ocean_hgrid37S_2.nc`
`/scratch/g40/wf4500/mom6_topo/shared/topog_37S.nc`

**Comment by willaguiar** [comment] 2023-03-16 00:52
> Ooops, sorry, brain was clearly not working!
> 
> I think they are these ones (@willaguiar can confirm these are the latest versions): `/scratch/g40/wf4500/mom6_topo/shared/ocean_hgrid37S_2.nc` `/scratch/g40/wf4500/mom6_topo/shared/topog_37S.nc`

Yes these should be the files for the 1/40th. ocean_mask.nc should be in the same directory too.

**Comment by micaeljtoliveira** [comment] 2023-03-16 03:04
@willaguiar To generate the computational mask, I need a ocean mosaic file. I generated it using the `make_solo_mosaic` utility, but it seems there's some inconsistency in the grid. When running `check_mask` I get the following error: 

`Error from read_mosaic: mismatch between refine_ratio and istart_in/iend_in`

I also tried to generate the exchange grid, but got another error, probably related:

`from read_mosaic_grid_sizes: ny is not divided by y_refine`

Did I miss something?

**Comment by willaguiar** [comment] 2023-03-16 03:10
> @willaguiar To generate the computational mask, I need a ocean mosaic file. I generated it using the `make_solo_mosaic` utility, but it seems there's some inconsistency in the grid. When running `check_mask` I get the following error:
> 
> `Error from read_mosaic: mismatch between refine_ratio and istart_in/iend_in`
> 
> I also tried to generate the exchange grid, but got another error, probably related:
> 
> `from read_mosaic_grid_sizes: ny is not divided by y_refine`
> 
> Did I miss something?

@micaeljtoliveira I just transferred to the folder the mosaic I previously created:
/scratch/g40/wf4500/mom6_topo/shared/ocean_mosaic.nc

Let me know in case you need the land and atmospheric mosaic too.

**Comment by willaguiar** [comment] 2023-03-16 03:19
@micaeljtoliveira Some information that probably is useful:
To create the ocean_mask.nc I used the ocean_hgrid37S.nc instead of ocean_hgrid37S_2.nc.  ocean_hgrid37S.nc has ny=nyp-2, and  ocean_hgrid37S_2.nc has ny=nyp-1.
For some reason having ny=nyp-1 in ocean_hgrid37S_2.nc would generate the same errors you found when using make_solo_mosaic and check_mask. But both tools worked fine in a grid with ny=nyp-2 (i.e., ocean_hgrid37S.nc).

**Comment by adele157** [comment] 2023-03-16 05:40
Update: the Sapphire Rapids are being publicly released next Wednesday! @willaguiar, @fabiobdias or others, it would be awesome if you have any time available to try to make this 1/40th config happen!

**Comment by micaeljtoliveira** [comment] 2023-03-16 09:18
That's strange. I suspect that you cut the grid in the wrong place and were left with half cells. Normally `nyp` must be odd and `ny` should always be `nyp-1`. @angus-g Could you confirm this?

**Comment by angus-g** [comment] 2023-03-16 09:28
> Normally `nyp` must be odd and `ny` should always be `nyp-1`. @angus-g Could you confirm this?

I don't think that `nyp` must be odd, it just defines the number of cell edges. So a single-cell grid would have `nyp=2` And `ny` defines the number of cell centres which should indeed be `nyp-1`.

**Comment by willaguiar** [comment] 2023-03-17 04:33
@angus-g @micaeljtoliveira I knew that ny should be = nyp-1, but didn't realized nyp should be odd (makes sense). That is probably why I was having the same error as  @micaeljtoliveira. 

I remade the grid and masks, (now with nyp odd) and updated the files  now. 
List of files:
ocean grid: /scratch/g40/wf4500/mom6_topo/shared/ocean_hgrid_panant0025.nc
ocean topography: /scratch/g40/wf4500/mom6_topo/shared/topog_panant0025.nc
ocean mask: /scratch/g40/wf4500/mom6_topo/shared/ocean_mask_panant0025.nc

**Comment by micaeljtoliveira** [comment] 2023-03-19 23:35
@willaguiar Thanks for fixing the issue with the grid!

I've now created three computational masks:
 - mask_table.580.100x25
 - mask_table.596.102x25
 - mask_table.1198.141x35

The first one uses 1920 cores and is suitable to use on Cascade Lake nodes. The second one uses 1954 cores and meant to be used with the Sapphire Rapids nodes. The last one uses roughly twice the number of cores of the previous ones (3737) and should be suitable for both Sapphire Rapids and Cascade Lake nodes.

I've also generated the mosaic and exchange grids. Have gathered all the files, including grid, topography and ocean mask in one place: `/g/data/ik11/inputs/mom6/panan/0025deg/20230320`

**Comment by adele157** [comment] 2023-03-22 19:32
Good news! The rerun panan-01 cases with yr2 ACCESS-OM2-01 or OM4 boundary forcing are looking good! They've only run a year so far, so I'll run out a bit more. But I think it's looking like we'll be able to switch the 1/20th and 1/40th to the new forcing. I guess we can see how these look after a few more years and decide whether we want OM4 or ACCESS-OM2-01 forcing.

<img width="673" alt="Screen Shot 2023-03-23 at 6 28 53 am" src="https://user-images.githubusercontent.com/8506963/227015573-70d37775-b23f-4706-91d5-53041c52e9aa.png">

**Comment by willaguiar** [comment] 2023-03-27 07:28
Hello everyone. I finished interpolating the boundary forcing (BF). The directory for the boundary forcing I created and for the initial conditions by @fabiobdias are listed in the end of the post. The BF for the 1/40th was created by interpolating the panant1/20th BF to the new grid.

I made some simple plots to compare the 1/20th and 1/40th BF [here](https://github.com/willaguiar/miscellanea/blob/59e78e3cfddd3f0fcb434d1807ae5d86a3b075d9/plot_regrids-2.ipynb) and they seem equal to me. But I need someone to confirm if the variables "ilist_segment_0001" and "jlist_segment_001" are correct. "ilist" seem to be a list of longitude indexes, but the "jlist" in the source file was a list of repeated values =1942 (so I'm not sure what it really means).

files:
Interpolated boundary forcing for 1/40th: /g/data/x77/wf4500/forcing_final_140th.nc
Interpolated initial conditions for 1/40th: /scratch/v45/fbd581/mom6-panan/scripts/temp_salt_init_z_panant0025.nc

**Comment by willaguiar** [comment] 2023-03-29 07:15
> @willaguiar Thanks for fixing the issue with the grid!
> 
> I've now created three computational masks:
> 
> * mask_table.580.100x25
> * mask_table.596.102x25
> * mask_table.1198.141x35
> 
> The first one uses 1920 cores and is suitable to use on Cascade Lake nodes. The second one uses 1954 cores and meant to be used with the Sapphire Rapids nodes. The last one uses roughly twice the number of cores of the previous ones (3737) and should be suitable for both Sapphire Rapids and Cascade Lake nodes.
> 
> I've also generated the mosaic and exchange grids. I have gathered all the files, including grid, topography and ocean mask in one place: `/g/data/ik11/inputs/mom6/panan/0025deg/20230320`

I tried to run Panan-0025 but the run is killed with the following error on mom6.out
**68 total processes killed (some possibly by mpirun during cleanup)**
and on error log
**Model exited with error code 137; aborting.**
@micaeljtoliveira Could that be related to the computational masks?

**Comment by adele157** [comment] 2023-03-29 18:57
What's the path of your run directory? Might be helpful to see how far it
got through initialisation or if there are any other error messages.

**Comment by willaguiar** [comment] 2023-03-29 22:22
It crashes right when it initializes. mom6.err/out seem to indicate a problem with y in the hgrid 
 dir: `/home/156/wf4500/mom6-panan`

mom6.out:
 ```
NOTE from PE     0: grid_mod/get_grid_cell_vertices: domain is not present, global data will be read
NOTE from PE     0: MPP_IO_SET_STACK_SIZE: stack size set to  194896367.
NOTE from PE     0: grid_mod/get_grid_cell_centers: domain is not present, global data will be read
```
mom5.err

`FATAL from PE   504: NETCDF ERROR: NetCDF: HDF error File=INPUT/ocean_hgrid.nc Field=y`

**Comment by willaguiar** [comment] 2023-03-30 04:17
> It crashes right when it initializes. mom6.err/out seem to indicate a problem with y in the hgrid dir: `/scratch/g40/wf4500/mom6/`
> 
> mom6.out:
> 
> ```
> NOTE from PE     0: grid_mod/get_grid_cell_vertices: domain is not present, global data will be read
> NOTE from PE     0: MPP_IO_SET_STACK_SIZE: stack size set to  194896367.
> NOTE from PE     0: grid_mod/get_grid_cell_centers: domain is not present, global data will be read
> ```
> 
> mom5.err
> 
> `FATAL from PE 504: NETCDF ERROR: NetCDF: HDF error File=INPUT/ocean_hgrid.nc Field=y`

It seems that a similar grid error with MOM5 happened (at least on mom.out) [here](https://github.com/mom-ocean/MOM5/issues/177#issuecomment-311823064).

Does anybody know what was the solution for that one?

**Comment by micaeljtoliveira** [comment] 2023-03-30 04:44
@willaguiar I think you forgot to update `NIGLOBAL` and `NJGLOBAL` in the `MOM_input` and `SIS_input` files. I believe these should be:
```
NIGLOBAL = 14400
NJGLOBAL = 3383
```
This seems to work, but then the run crashes because of not enough memory. I then switched to using 3737 cores on the new Sapphire Rapids nodes, but still crashed by lack of memory.

I will try to create a new mask using a larger number of cores and see how that goes.

**Comment by willaguiar** [comment] 2023-03-30 04:48
> @willaguiar I think you forgot to update `NIGLOBAL` and `NJGLOBAL` in the `MOM_input` and `SIS_input` files. I believe these should be:
> 
> ```
> NIGLOBAL = 14400
> NJGLOBAL = 3383
> ```
> 
> This seems to work, but then the run crashes because of not enough memory. I then switched to using 3737 cores on the new Sapphire Rapids nodes, but still crashed by lack of memory.
> 


Yeppp. I updated N*GLOBAL in other tries and it gave the same error. We just realized it was memory problem too. 

> I will try to create a new mask using a larger number of cores and see how that goes.

thanks!

**Comment by angus-g** [comment] 2023-03-30 04:55
We did discover that if you don't explicitly set the layout for the (null) atmos/land models, you can get some pretty bad layouts! Using 1954 cores, that's only divisible by 2 and 977, so you get a lot of extremely thin tiles in those components. They're not doing anything significant, but it probably harms IO through the coupler... I think maybe we should set the layout (and mask) to match the ocean/ice models: in `input.nml`:

```
&atmos_model_nml
    layout = X,Y
    mask_table = 'INPUT/mask_table_name'
/

&land_model_nml
    layout = X,Y
    mask_table ='INPUT/mask_table_name'
/
```

**Comment by micaeljtoliveira** [comment] 2023-03-30 05:05
I just tried it with 7563 cores, which corresponds to 13.69TB of memory, but it still did not work. Need more cores... Unfortunately I won't be able to try this until tonight.

In the meantime, is there a way to roughly estimate the total memory needed by a MOM6 calculation based on the number of grid points?

**Comment by willaguiar** [comment] 2023-03-30 11:19
> It seems I've got something that runs! It still crashes, but it seems that's because I don't have permissions to read `/home/156/wf4500/mom6-panan/input_1_40th/` . The main issue was my lack of experience with payu. When switching to the Sapphire Rapid nodes I forgot to explicitly add the amount of memory to request. These nodes have 512Gb memory each, so we there was a lot more available than what payu was requesting.
> 
> In any case, I generated a new mask, as we will definitely need to use more cores so that this runs fast enough. I also added the layout and mask for the atmos/land models. I also set the IO_LAYOUT to a more reasonable value. My files are here: `/scratch/g40/mo1833/mom6/work/0.025`

Thanks so much Micael! I opened permissions for the '/home/156/wf4500/mom6-panan/input_1_40th/' now. Imma try to run it in my dir too.

**Comment by willaguiar** [comment] 2023-03-31 05:31
update. Memory, mask problem is gone now with the new mask_table.2431.204x48 file and 7361 cpus. 

panan0025 runs, but it crashes with the following error:

`FATAL from PE  7280: Invalid data type for dimension`

It doesn't point to a specific file tho. **Can someone tell me what comes after those lines below on panan005 runs?** It might help me identify which input file has invalid data type.

```
MOM_in domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36
             36  36  36  36  36  36  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35
             35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35
             35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35
             35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35
             35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35
             35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35
             35  35  35  35  35  35  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36
             36  36  36  36  36  36  36  36  36  36  36  36
  Y-AXIS =   36  36  36  36  36  36  36  36  36  36  36  35  35  35  35  35  35  35  35  35  35  35  35  35
             35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35  35
```

directory for the run: /scratch/g40/wf4500/experiments2/wf4500/mom6/

**Comment by adele157** [comment] 2023-03-31 05:34
You could compare against this 1/20th run:

/scratch/x77/akm157/mom6/archive/panan-005-zstar-ACCESSyr2/

**Comment by willaguiar** [comment] 2023-04-01 00:11
Update and good news!
Problem above was caused because the boundary forcing had dimensions in _int64_ instead of _int_. Other errors appeared, but were fixed by setting time as record dimension in the boundary forcing, and adding coordinates as data in the initial conditions file.

**Good news is ....** I was able to run panan0025 for 1 model day without any error messages! 
**Caveat:** memory was still too low, and the run was killed after 1 model day because of lack of memory (~30TB). I will request a higher memory and rerun it. 


**new BF:** `/g/data/x77/wf4500/mom6-panan-1_40th/forcing_final_140th_int3.nc`
**new IC:** `/scratch/v45/fbd581/mom6-panan/scripts/temp_salt_init_z_panant0025_31032023.nc`

perhaps someone with writing permissions to  `/g/data/ik11/inputs/mom6/panan/0025deg/20230320` should add these files to that folder, since they are working fine now.

On another note.... Since we have the model running now, should we already change the bathymetry as in [here](https://github.com/COSIMA/mom6-panan/issues/34#issuecomment-1492708219), before doing another run?

**Comment by adele157** [comment] 2023-04-01 04:55
Great that it's running! Yes, let's update the bathymetry. I can do it so it's the same as the 1/20th that I just did.

**Comment by adele157** [comment] 2023-04-01 05:23
Update: I have edited the `depth` variable in the topography files for the 1/20th and 1/40th here:
`/g/data/v45/akm157/inputs/mom6/panan/panan_0025/topog_edited.nc` and
`/g/data/v45/akm157/inputs/mom6/panan/panan_005/topog_edited.nc`

But... I haven't changed the `sea_area_fraction` variable, as I'm not sure how that's supposed to be set. And I haven't redone any of the masks.

**Comment by willaguiar** [comment] 2023-04-01 08:15
On the mask subject... I rerun panan0025 using mask_table3093.220x56 (9227 ncpus, 46Tb) and the run still crashed within 1 model day due to lack of memory.  (Perhaps we will need a mask that supports more cpus).

**Comment by micaeljtoliveira** [comment] 2023-04-03 00:44
> On the mask subject... I rerun panan0025 using mask_table3093.220x56 (9227 ncpus, 46Tb) and the run still crashed within 1 model day due to lack of memory. (Perhaps we will need a mask that supports more cpus).

I had a look at the scaling tests I did with the lower resolution configurations, and it seems that the memory used increases with the number of cores almost linearly. Although some increase is to be expected, a linear increase means that there's a some large data duplicated among cores, which in turn means that just increasing the number of cores might not solve out problem.

The fact that the problem only shows up after 1 model day might indicate that it happens during I/O. I'm assuming you are doing some daily output?

@angus-g Any thoughts on this?

**Comment by willaguiar** [comment] 2023-04-03 00:58
> > On the mask subject... I rerun panan0025 using mask_table3093.220x56 (9227 ncpus, 46Tb) and the run still crashed within 1 model day due to lack of memory. (Perhaps we will need a mask that supports more cpus).
> 
> I had a look at the scaling tests I did with the lower resolution configurations, and it seems that the memory used increases with the number of cores almost linearly. Although some increase is to be expected, a linear increase means that there's a some large data duplicated among cores, which in turn means that just increasing the number of cores might not solve out problem.
> 

Hi @micaeljtoliveira @angus-g 

I was looking digging into the error logs today and found the crash doesn't happen due to memory -  sorry. I thought that before because the total memory used was ~40Tb close to the total requested, but it turns out the crash wasn't because of it).

> The fact that the problem only shows up after 1 model day might indicate that it happens during I/O. I'm assuming you are doing some daily output?

Yes, I was running a 3-days test just to see if the model ran.

The actual model error seem to be due to a mismatch between the BF dates and the run dates. 

`FATAL from PE  9055: time_interp_external 2: time 726350 (19910101.001500 is after range of list 693135-693499(19000101.120000 - 19001231.120000),file=INPUT/forcing_final_140th_int3.nc,field=u_segment_001`

The weird thing tho is that on the forcing file for the 1/20th the time is exactly the same, and so is the current_date on input.nml (current_date = 1991, 1, 1, 0, 0, 0) between the runs. I will alter the date in the BF file to see if the problem is fixed tho.

**Comment by angus-g** [comment] 2023-04-03 00:59
@willaguiar You need to set the`modulo` attribute on the forcing, something like:
```
ncatted -O -a "modulo,time,a,c " forcing.nc
```

**Comment by micaeljtoliveira** [comment] 2023-04-03 01:04
@angus-g I've set the IO layout to `51,12`, for a core layout of `204,48`, as it seemed that doing the I/O on a single core was not really a reasonable option anymore with such a high resolution. Not sure if this layout is a good choice though. At least it looked reasonable to me...

**Comment by angus-g** [comment] 2023-04-03 01:07
I think the ideal would be for the IO layout to line up with the nodes (i.e. one IO core per node), but I guess FMS doesn't have any notion of the physical layout of the cores. Sounds reasonable to me too!

**Comment by willaguiar** [comment] 2023-04-11 06:35
Panan 1/40th is now running smooth with the new topography, and initial conditions and bathymetry for year 2 of OM2-01. Running 2 model days with 9227 CPUs takes 23 minutes walltime ( not counting initialization and checksum). So we will need more than 5hrs to run a full month. 

@micaeljtoliveira   , do you think it is worth increasing/doubling the cpus so we can have monthly outputs? Alternatively we can ask for an exception to run the model for more than 5hrs

**Comment by micaeljtoliveira** [comment] 2023-04-11 22:53
@willaguiar I can try to find the best number of cores to get a full month done under 5 hours. I was anyway planning to do a scaling test as soon as we had something working, so it's good to have a clear target for it. Probably also worth tuning the I/O layout.

**Comment by micaeljtoliveira** [comment] 2023-04-11 23:21
@willaguiar Could you create a new branch for your 1/40th degree configuration and push it, so that I can use it for my tests?

**Comment by willaguiar** [comment] 2023-04-12 01:39
@micaeljtoliveira just done it! Branch named panan-0025

**Comment by adele157** [comment] 2023-04-12 23:29
FYI, I’ve also asked NCI if we can have a longer wall time limit for the
1/40th runs, and I think they will approve (have asked for 10 hrs). Though
it would still be good to run on more cores if possible to get a bit faster
throughput, if the scaling is not too terrible.

**Comment by micaeljtoliveira** [comment] 2023-04-16 23:21
Looks like the maximum number of cores one can use with the Sapphire Rapids nodes is 10400, so I'm now trying to find out what is the maximum number of cores we can use with our configuration within that limit. I've got a reasonable candidate (10383 cores), but I need to check that it runs fine.

**Comment by aekiss** [comment] 2023-04-16 23:56
10400 seems very low - that's less than the 12144 we were using on cascade lake. What sets this limit?

**Comment by micaeljtoliveira** [comment] 2023-04-16 23:57
It's a queue limit: https://opus.nci.org.au/display/Help/Queue+Limits

**Comment by aekiss** [comment] 2023-04-17 00:27
There are about half as many sapphire rapid cores as cascade lake (74880 vs 147552  https://nci.org.au/our-systems/hpc-systems) so I guess that's why the halved the maximum core count. But 10400 is only ~14% of the cores so they could increase the limit if they wanted.

@adele157 can you ask your contact at NCI why here's such a low core count limit on sapphire rapids? The limit they've set (10400) will make it impossible for us to run our normal production configuration for ACCESS-OM2-01-BGC (12144 cores) on the new nodes.

**Comment by micaeljtoliveira** [comment] 2023-04-17 00:53
Using 10383 cores seems to works fine (my run reached the main loop) but I didn't get any timings. It would also be good to optimize the IO layout. Unfortunately these tests are using a lot of SU's (> 30 KSU), so it's better to discuss the next steps during the weekly meeting.

**Comment by adele157** [comment] 2023-04-17 05:02
I’m guessing you’ve already discussed this today, but I’m case it’s useful:

We have enough hours for testing Micael, go for it (ol01 or elsewhere).

I can ask if they can increase our SU limit too, what number would we want?

**Comment by micaeljtoliveira** [comment] 2023-04-17 05:08
@adele157 Thanks! 

Looks like we have used almost all the hours in `ol01`. I seem to remember there was a specific project with hours for the Sapphire Rapids nodes. Is it still the case? Otherwise what's the best project for this? `e14`? Note that just the testing is likely use a few hundred thousand SU's, as a short run with ~10000 cores uses 30-40 KSU.

**Comment by adele157** [comment] 2023-04-17 05:15
Yes, ot56, go for it!

**Comment by micaeljtoliveira** [comment] 2023-04-18 00:38
I now have the timings when using 10383 cores. Unfortunately it still takes too long: two simulation days take a bit over 20 minutes walltime. This means we definitely need a higher core count or a longer walltime.

**Comment by adele157** [comment] 2023-04-18 07:47
Wilton can now run 10 hours on 100 nodes (10400 cores) on normalsr on
project ot56. Probably we need access for Micael also? Is this number of
cores ok, or do we need to increase slightly to accomodate the tests you’ve
been doing on 10383 cores?

**Comment by willaguiar** [comment] 2023-04-18 08:23
Yes! I responded the NCI ticket asking to add Micael to the walltime exception, and also with a request to increase the ncores. @micaeljtoliveira is still running some tests to find the optimal configuration (which could be slightly above the queue ncores limit), so in the last meeting we decided to ask for an increase in the ncores for these runs.

> Wilton can now run 10 hours on 100 nodes (10400 cores) on normalsr on project ot56. Probably we need access for Micael also? Is this number of cores ok, or do we need to increase slightly to accomodate the tests you’ve been doing on 10383 cores?
> […](#)

**Comment by micaeljtoliveira** [comment] 2023-04-20 00:03
After a few more tests, I got to the conclusion it was best to use slightly less cores (9872) and a different IO layout. It takes almost the same time to run one month (~6h20), but uses less SU's (~125 KSU instead of ~129 KSU).

Unfortunately the initialization and termination still take a large fraction of the total walltime (~15%), so it might be worth trying to do 2 months per run, but for that we need to use more cores than the current limit.

I'll update the panan-0025 branch with the new core count and mask.

@angus-g It looks like the best IO layout is to have roughly one IO core per compute node, as you predicted!

**Comment by angus-g** [comment] 2023-04-20 00:33
> @angus-g It looks like the best IO layout is to have roughly one IO core per compute node, as you predicted!

Glad to know the theory still applies in practice. Thanks for doing these tests! I can look into whether we can get any easy wins for initialisation/termination so it's not such a large chunk of a run segment?

**Comment by micaeljtoliveira** [comment] 2023-04-20 01:12
> I can look into whether we can get any easy wins for initialisation/termination so it's not such a large chunk of a run segment?
That would be great!

**Comment by angus-g** [comment] 2023-04-20 08:06
A simple one that I don't know how we missed: `PARALLEL_RESTARTFILES` will write one restart file per IO core, which at least speeds up the termination significantly. This option can be used for both MOM and SIS, although I forgot to set a non-unity IO layout for SIS, so it only applies to MOM for the numbers here.

Then for the test run I did, of the 70s initialisation time, 26s was in setting up the exchange grid, 15s in initialising SIS, and 13s initialising MOM. It also brought the termination time down to about 30s from 210s.

**Comment by micaeljtoliveira** [comment] 2023-04-23 22:18
@angus-g Thanks! I've tried setting `PARALLEL_RESTARTFILES` and  `IO_LAYOUT` for both MOM and SIS. In my tests, this brings the initialization down to 424s from 750s and termination down to 44s from 2376s. Now when propagating one month,  initialization and termination take under 3%, which is more than acceptable. So this is not an issue anymore.

I'll update the configuration ASAP.

**Comment by adele157** [comment] 2023-04-23 22:28
Amazing! Great work Micael and Angus!

**Comment by adele157** [comment] 2023-04-24 02:30
@micaeljtoliveira a follow up on this initialisation/termination speed up - can we also take advantage of this in the 1/20th panan?

**Comment by micaeljtoliveira** [comment] 2023-04-24 22:25
@adele157 Yes, sure. I'll get a couple of tests running to find the optimal IO layout.

**Comment by micaeljtoliveira** [comment] 2023-04-25 22:21
I've now update the test-1/20th branch to use a better IO layout, write the restart in parallel and to use the sapphire rapids nodes. With all these changes, initialization and termination take around 40s and running a full month takes ~2h walltime.

**Closed** 2023-05-17 01:27 UTC
